"""Domain services - business logic layer (Firestore-backed)."""

from app.services.auth_service import (
    get_user_by_id,
    get_user_by_email,
    get_user_by_username,
    get_or_create_user_from_firebase,
    update_user,
    list_users,
    soft_delete_user,
    AuthError,
    UserAlreadyExistsError,
    InvalidCredentialsError,
    UserNotFoundError,
)

from app.services.workspace_service import (
    create_workspace,
    get_workspace_by_id,
    get_workspace_by_slug,
    list_user_workspaces,
    update_workspace,
    delete_workspace,
    add_member,
    update_member_role,
    remove_member,
    list_members,
    get_member_count,
    get_workspace_membership,
    MembershipRole,
    WorkspaceError,
    WorkspaceNotFoundError,
    WorkspaceAccessDeniedError,
)

from app.services.agent_service import (
    create_agent,
    get_agent_by_id,
    list_workspace_agents,
    update_agent,
    delete_agent,
    create_execution,
    get_execution_by_id,
    list_agent_executions,
    start_execution,
    complete_execution,
    fail_execution,
    cancel_execution,
    pause_execution,
    resume_execution,
    list_session_executions,
    AgentStatus,
    ExecutionStatus,
    AgentError,
    AgentNotFoundError,
    InvalidTransitionError,
)

from app.services.tool_service import (
    create_tool,
    get_tool_by_id,
    get_tool_by_slug,
    list_workspace_tools,
    list_public_tools,
    update_tool,
    delete_tool,
    create_tool_execution,
    complete_tool_execution,
    fail_tool_execution,
    list_tool_executions,
    ToolError,
    ToolNotFoundError,
    ToolSlugTakenError,
)

from app.services.mcp_service import (
    route_chat_completion,
    get_available_models,
    seed_default_models,
    get_cost_summary,
    get_cost_by_provider,
    get_cost_by_model,
    get_recent_calls,
    calculate_cost,
    DEFAULT_MODEL_PRICING,
)

from app.services.prompt_service import (
    create_prompt,
    get_prompt_by_id,
    list_workspace_prompts,
    update_prompt,
    delete_prompt,
    create_version,
    get_version,
    get_current_version,
    list_versions,
    rollback_to_version,
    render_prompt,
    PromptError,
    PromptNotFoundError,
    VersionNotFoundError,
    PromptSlugTakenError,
)

from app.services.workflow_service import (
    create_workflow,
    get_workflow_by_id,
    list_workspace_workflows,
    update_workflow,
    delete_workflow,
    get_execution,
    list_executions,
    request_approval,
    approve_execution,
    validate_dag,
    WorkflowError,
    WorkflowNotFoundError,
    InvalidDAGError,
)

from app.services.memory_service import (
    create_entry,
    get_entry,
    list_session_memory,
    list_agent_memory,
    delete_entry,
    clear_session,
    search_memory,
    consolidate_session_memory,
    update_importance,
    MemoryError,
)

from app.services.secret_service import (
    create_secret,
    get_secret_by_id,
    get_secret_value,
    list_workspace_secrets,
    update_secret,
    delete_secret,
    encrypt_value,
    decrypt_value,
    SecretError,
    SecretNotFoundError,
    SecretSlugTakenError,
)

from app.services.artifact_service import (
    create_artifact,
    get_artifact_by_id,
    list_workspace_artifacts,
    update_artifact,
    delete_artifact,
    ArtifactError,
    ArtifactNotFoundError,
)

from app.services.execution_graph_service import (
    create_node,
    get_node_by_id,
    update_node_status,
    list_execution_nodes,
    get_execution_graph,
    get_node_children,
    ExecutionGraphError,
    NodeNotFoundError,
)

from app.services.telemetry_service import (
    create_event,
    get_event_by_id,
    list_events,
    create_audit_log,
    list_audit_logs,
    get_workspace_stats,
    TelemetryError,
    TelemetryEventNotFoundError,
)

__all__ = [
    # Auth
    "get_user_by_id",
    "get_user_by_email",
    "get_user_by_username",
    "get_or_create_user_from_firebase",
    "update_user",
    "list_users",
    "soft_delete_user",
    "AuthError",
    "UserAlreadyExistsError",
    "InvalidCredentialsError",
    "UserNotFoundError",
    # Workspace
    "create_workspace",
    "get_workspace_by_id",
    "get_workspace_by_slug",
    "list_user_workspaces",
    "update_workspace",
    "delete_workspace",
    "add_member",
    "update_member_role",
    "remove_member",
    "list_members",
    "get_member_count",
    "get_workspace_membership",
    "MembershipRole",
    "WorkspaceError",
    "WorkspaceNotFoundError",
    "WorkspaceAccessDeniedError",
    # Agent
    "create_agent",
    "get_agent_by_id",
    "list_workspace_agents",
    "update_agent",
    "delete_agent",
    "create_execution",
    "get_execution_by_id",
    "list_agent_executions",
    "start_execution",
    "complete_execution",
    "fail_execution",
    "cancel_execution",
    "pause_execution",
    "resume_execution",
    "list_session_executions",
    "AgentStatus",
    "ExecutionStatus",
    "AgentError",
    "AgentNotFoundError",
    "InvalidTransitionError",
    # Tool
    "create_tool",
    "get_tool_by_id",
    "get_tool_by_slug",
    "list_workspace_tools",
    "list_public_tools",
    "update_tool",
    "delete_tool",
    "create_tool_execution",
    "complete_tool_execution",
    "fail_tool_execution",
    "list_tool_executions",
    "ToolError",
    "ToolNotFoundError",
    "ToolSlugTakenError",
    # MCP
    "route_chat_completion",
    "get_available_models",
    "seed_default_models",
    "get_cost_summary",
    "get_cost_by_provider",
    "get_cost_by_model",
    "get_recent_calls",
    "calculate_cost",
    "DEFAULT_MODEL_PRICING",
    # Prompt
    "create_prompt",
    "get_prompt_by_id",
    "list_workspace_prompts",
    "update_prompt",
    "delete_prompt",
    "create_version",
    "get_version",
    "get_current_version",
    "list_versions",
    "rollback_to_version",
    "render_prompt",
    "PromptError",
    "PromptNotFoundError",
    "VersionNotFoundError",
    "PromptSlugTakenError",
    # Workflow
    "create_workflow",
    "get_workflow_by_id",
    "list_workspace_workflows",
    "update_workflow",
    "delete_workflow",
    "get_execution",
    "list_executions",
    "request_approval",
    "approve_execution",
    "validate_dag",
    "WorkflowError",
    "WorkflowNotFoundError",
    "InvalidDAGError",
    # Memory
    "create_entry",
    "get_entry",
    "list_session_memory",
    "list_agent_memory",
    "delete_entry",
    "clear_session",
    "search_memory",
    "consolidate_session_memory",
    "update_importance",
    "MemoryError",
    # Secrets
    "create_secret",
    "get_secret_by_id",
    "get_secret_value",
    "list_workspace_secrets",
    "update_secret",
    "delete_secret",
    "encrypt_value",
    "decrypt_value",
    "SecretError",
    "SecretNotFoundError",
    "SecretSlugTakenError",
    # Artifacts
    "create_artifact",
    "get_artifact_by_id",
    "list_workspace_artifacts",
    "update_artifact",
    "delete_artifact",
    "ArtifactError",
    "ArtifactNotFoundError",
    # Execution Graph
    "create_node",
    "get_node_by_id",
    "update_node_status",
    "list_execution_nodes",
    "get_execution_graph",
    "get_node_children",
    "ExecutionGraphError",
    "NodeNotFoundError",
    # Telemetry
    "create_event",
    "get_event_by_id",
    "list_events",
    "create_audit_log",
    "list_audit_logs",
    "get_workspace_stats",
    "TelemetryError",
    "TelemetryEventNotFoundError",
]
